# Site settings
title: 九里香
email: ykjver@163.com
description: > # this means to ignore newlines until "baseurl:"
  他们都说我长得帅
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://bolg.ykjver.com" # the base hostname & protocol for your site
twitter_username: lvsekedou
github_username:  ykjver

# Build settings
markdown: kramdown
encoding: utf-8
