# Site settings
title: 黑子草
email: 386047968@qq.com
description: 定性、知事、选梦、遇人、伴城终老！
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.huangh.xyz/" # the base hostname & protocol for your site
twitter_username: 
github_username:  huanghuihong

# Build settings
markdown: kramdown
encoding: utf-8

theme: jekyll-theme-cayman